// js/car-presets.js
import { mphToPixels } from './utils.js';

export const CAR_TYPES = {
    drift: {
        id: 'drift',
        name: 'Drift King',
        description: 'Rear-biased setup built to hold long slides.',
        topSpeedMph: 66,
        topSpeed: mphToPixels(66),
        engineForce: mphToPixels(34),
        brakeForce: mphToPixels(62),
        handbrakeForce: mphToPixels(88),
        maxReverseSpeed: mphToPixels(28),
        mass: 1180,
        inertia: 2600,
        cgToFront: 88,
        cgToRear: 102,
        cornerStiffnessFront: 7200,
        cornerStiffnessRear: 5200,
        maxLateralForce: 13000,
        maxSteerAngle: 35,
        steerRate: 6.4,
        lateralDamping: 4.0,
        angularDamping: 2.9,
        longitudinalDrag: 0.26,
        rollingResistance: 7.6,
        health: 100,
        paint: {
            base: 0xc83434,
            secondary: 0x101010,
            accent: 0xffffff,
            decal: 'katana'
        }
    },
    balanced: {
        id: 'balanced',
        name: 'Apex GT',
        description: 'Stable all-rounder tuned for consistency.',
        topSpeedMph: 69,
        topSpeed: mphToPixels(69),
        engineForce: mphToPixels(36),
        brakeForce: mphToPixels(68),
        handbrakeForce: mphToPixels(80),
        maxReverseSpeed: mphToPixels(26),
        mass: 1240,
        inertia: 2850,
        cgToFront: 92,
        cgToRear: 96,
        cornerStiffnessFront: 8200,
        cornerStiffnessRear: 7600,
        maxLateralForce: 14200,
        maxSteerAngle: 32,
        steerRate: 6.1,
        lateralDamping: 4.6,
        angularDamping: 3.1,
        longitudinalDrag: 0.24,
        rollingResistance: 7.2,
        health: 102,
        paint: {
            base: 0x2874ff,
            secondary: 0x0f1b33,
            accent: 0xf7f9ff,
            decal: 'dualStripe'
        }
    },
    speedster: {
        id: 'speedster',
        name: 'Velocity RS',
        description: 'Higher top-end and lighter weight for sprints.',
        topSpeedMph: 73,
        topSpeed: mphToPixels(73),
        engineForce: mphToPixels(33),
        brakeForce: mphToPixels(54),
        handbrakeForce: mphToPixels(92),
        maxReverseSpeed: mphToPixels(25),
        mass: 1160,
        inertia: 2450,
        cgToFront: 94,
        cgToRear: 90,
        cornerStiffnessFront: 7600,
        cornerStiffnessRear: 6200,
        maxLateralForce: 12600,
        maxSteerAngle: 31,
        steerRate: 6.8,
        lateralDamping: 3.7,
        angularDamping: 2.6,
        longitudinalDrag: 0.28,
        rollingResistance: 6.4,
        health: 95,
        paint: {
            base: 0xff8b1f,
            secondary: 0x1b120c,
            accent: 0xfef2d5,
            decal: 'speedChevron'
        }
    },
    endurance: {
        id: 'endurance',
        name: 'Bulldog SX',
        description: 'Durable bruiser with dependable grip.',
        topSpeedMph: 62,
        topSpeed: mphToPixels(62),
        engineForce: mphToPixels(35),
        brakeForce: mphToPixels(72),
        handbrakeForce: mphToPixels(70),
        maxReverseSpeed: mphToPixels(24),
        mass: 1320,
        inertia: 3120,
        cgToFront: 86,
        cgToRear: 110,
        cornerStiffnessFront: 8800,
        cornerStiffnessRear: 8200,
        maxLateralForce: 15000,
        maxSteerAngle: 30,
        steerRate: 5.6,
        lateralDamping: 5.2,
        angularDamping: 3.4,
        longitudinalDrag: 0.22,
        rollingResistance: 8.2,
        health: 120,
        paint: {
            base: 0x4ad05f,
            secondary: 0x17311d,
            accent: 0xdfffdc,
            decal: 'enduranceBadge'
        }
    }
};